- name: Download wordpress
  get_url: url="http://ja.wordpress.org/latest-ja.tar.gz"
           dest=/tmp force=True

- name: Unarchive wordpress folder
  unarchive: remote_src=True src=/tmp/wordpress-4.9.7-ja.tar.gz dest=/tmp

#- name: Move wordpress directory
#  command: mv /tmp/wordpress /
#  ignore_errors: yes
#

#- name: Change Ownership
#  file: dest=/wordpress owner=apache group=apache mode=0775

- name: Set the owner of apache directory
  file: path=/tmp/wordpress owner=apache group=apache mode=0775 recurse=yes
  register: apacheResult

#- name: Change Ownership
#  file: path=/tmp/wordpress owner=root group=root mode=0775

#- name: Copy wordpress directory
#  copy: src=/home/vagrant/test/test.html dest=/home/vagrant/tes1
#  register: copyWordpress

# apacheをinstallしないと/var/wwwは存在しない
- name: Create symbolic link for appach
  file:
    src: /wordpress
    dest: "/var/www/html/wordpress"
    state: link

- name: Copy wp-config.php file
  template: src=wp-config.php dest=/wordpress/wp-config.php backup=yes

- name: Copy wordpress folder
  shell: cp -r /tmp/wordpress/* /wordpress
  when: apacheResult
